#!/usr/bin/python

import os, sys
import json

EXPECTED_ISSUE_KEYS = [u'Issue Title', u'IssueCode', u'IssueUrl', u'Pages', u'SubTitle']

def check_json(issue):
    keys = sorted(issue.keys())
    if keys != EXPECTED_ISSUE_KEYS:
        raise ValueError("Got unexpected keys %s", keys)


def parse_json(fn):
    print fn
    f = open(fn)
    issue = json.load(f)
    f.close()
    check_json(issue)


def main():
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument('files', nargs='+',
                        help='files to process')
    args = parser.parse_args()

    for fn in args.files:
        parse_json(fn)

main()
