#!/usr/bin/python
import sys
import os
from alphabet import read_header, BOOK_HEADERS, STX, ETX

DEST_DIR = os.path.join(os.path.dirname(__file__), 'books/chapters')


def split_book(fn, target_size):
    f = open(fn)
    headers, here = read_header(f)
    end = os.fstat(f.fileno()).st_size
    remaining = end - here
    n_chapters = max(1, remaining // target_size)
    chapters = []
    chapter = []
    size = remaining // n_chapters
    next_stop = here + size
    print >> sys.stderr, ("here %s, end %s, target %s, n_chapters %s, size %s"
                          % (here, end, target_size, n_chapters, size))
    for line in f:
        here += len(line)
        line = line.rstrip()
        if ((line == '' and here >= next_stop) or
            (here >= next_stop + size // 8 and n_chapters > 1)):
            if line:
                chapter.append(line)
                print >>sys.stderr, ("missed line break %d in %s at %s"
                                     " wanted %s" %
                                     (len(chapters), fn, here, next_stop))
            chapter.append(ETX)
            chapters.append('\n'.join(chapter))
            n_chapters = max(1, remaining // target_size)
            remaining = end - here
            if not remaining:
                break
            size = remaining // n_chapters
            next_stop = here + size
            chapter = []
        elif chapter == []:
            chapter.append(STX + line)
        else:
            chapter.append(line)

    chapters.append(''.join(chapter))
    return headers, chapters


def main():
    for book in sys.argv[1:]:
        if not os.path.isfile(book):
            continue
        print >> sys.stderr, "doing %s" % book
        headers, chapters = split_book(book, 5000)
        headers['type'] = 'chapter'
        base_id = headers['id']
        base_title = headers['title']
        for i, chapter in enumerate(chapters):
            id_ = '%s-%03d' % (base_id, i + 1)
            headers['id'] = id_
            headers['title'] = '%s (part %s)' % (base_title, i + 1)
            header = ''.join("%s: %s\n" % (k, headers[k])
                             for k in BOOK_HEADERS)
            f = open(os.path.join(DEST_DIR, id_), 'w')
            print >> f, header
            print >> f, chapter
            f.close()

main()
